export const COMPANY_INFO = {
  name: 'Shueki Tech',
  tagline: 'Engineering Solutions That Drive Innovation',
  email: 'info@shuekitech.com',
  phone: '+91-84271-82071',
  address: 'Opposite UCO Bank, Ground Floor, Hoshiarpur Road, Garhshankar, Punjab - 144527',
  timezone: 'IST (UTC+5:30)',
  stats: {
    projects: '50+',
    clients: '30+',
    experience: '10+',
  },
}

export const NAVIGATION_LINKS = [
  { name: 'Home', path: '/' },
  { name: 'Services', path: '/services' },
  { name: 'Projects', path: '/projects' },
  { name: 'About', path: '/about' },
  { name: 'Contact', path: '/contact' },
]

export const PROJECTS = [
  {
    id: 'ecommerce-platform',
    title: 'Multi-Vendor E-Commerce Platform',
    client: 'Anonymous',
    industry: 'Retail',
    service: 'web-development',
    problem: 'Client needed a scalable multi-vendor marketplace with integrated payment gateway and vendor management dashboard.',
    result: '3x increase in sales within 6 months. 50+ vendors onboarded at launch.',
    tech: ['React', 'Laravel', 'PostgreSQL', 'Stripe', 'AWS'],
    featured: true,
    year: 2024,
    gradient: 'from-blue-500 to-cyan-500',
  },
  {
    id: 'factory-automation',
    title: 'Automated Quality Control System',
    client: 'Anonymous',
    industry: 'Manufacturing',
    service: 'machine-integration',
    problem: 'Manual inspection caused an 8% defect rate reaching customers and significant production downtime.',
    result: 'Defect rate reduced to 0.3%. Line throughput improved by 40%.',
    tech: ['PLC/SCADA', 'Python', 'OpenCV', 'MQTT', 'OPC-UA'],
    featured: true,
    year: 2024,
    gradient: 'from-orange-500 to-red-500',
  },
  {
    id: 'ai-customer-support',
    title: 'AI-Powered Customer Support Pipeline',
    client: 'Anonymous',
    industry: 'SaaS',
    service: 'ai-pipelines',
    problem: 'Support team was overwhelmed with repetitive tickets. Average response time was 18 hours.',
    result: 'Auto-resolved 65% of tickets. Average response time dropped to under 2 minutes.',
    tech: ['Python', 'LangChain', 'OpenAI', 'n8n', 'PostgreSQL'],
    featured: true,
    year: 2024,
    gradient: 'from-purple-500 to-pink-500',
  },
  {
    id: 'iot-pcb-design',
    title: 'Industrial IoT Sensor Board',
    client: 'Anonymous',
    industry: 'Industrial IoT',
    service: 'pcb-designing',
    problem: 'Client needed a compact 4-layer PCB for real-time temperature and vibration monitoring in harsh environments.',
    result: 'Production-ready design delivered in 3 weeks. Board passed all certifications on first run.',
    tech: ['KiCAD', 'ESP32', 'MQTT', 'LTSpice', 'JLCPCB'],
    featured: true,
    year: 2023,
    gradient: 'from-green-500 to-teal-500',
  },
  {
    id: 'fleet-tracking-app',
    title: 'Fleet Tracking Mobile App',
    client: 'Anonymous',
    industry: 'Logistics',
    service: 'app-development',
    problem: 'Operations team had no real-time fleet visibility, causing delivery delays and fuel wastage.',
    result: 'Delivery accuracy improved by 28%. Fuel costs reduced by 15%.',
    tech: ['React Native', 'Firebase', 'Google Maps API', 'Redux'],
    featured: false,
    year: 2023,
    gradient: 'from-yellow-500 to-orange-500',
  },
  {
    id: 'smart-irrigation-rd',
    title: 'Smart Irrigation R&D Consultancy',
    client: 'Anonymous',
    industry: 'AgriTech',
    service: 'rd-consultancy',
    problem: 'Startup needed a technical feasibility study and PoC for an AI-based irrigation control system.',
    result: 'PoC delivered in 6 weeks. Client secured seed funding based on the technical prototype.',
    tech: ['Python', 'Raspberry Pi', 'MQTT', 'TensorFlow Lite'],
    featured: false,
    year: 2023,
    gradient: 'from-lime-500 to-green-600',
  },
]

export const SERVICES = [
  {
    id: 'web-development',
    title: 'Website Development',
    icon: 'Globe',
    description: 'Full-stack web applications, e-commerce platforms, and custom portals built with modern frameworks.',
    features: [
      'Custom web application development',
      'E-commerce platforms & payment integration',
      'Progressive Web Apps (PWA)',
      'API development & third-party integrations',
      'Admin dashboards & CMS solutions',
    ],
    tech: ['React', 'Node.js', 'Laravel', 'PostgreSQL', 'AWS', 'Tailwind CSS'],
  },
  {
    id: 'machine-integration',
    title: 'Machine Integration & Automation',
    icon: 'Cog',
    description: 'Industrial automation solutions including PLC/SCADA programming, robotics integration, and smart factory systems.',
    features: [
      'PLC & SCADA programming',
      'Industrial robotics integration',
      'IoT-enabled machine monitoring',
      'Process automation & optimization',
      'HMI design & development',
    ],
    tech: ['PLC/SCADA', 'ROS2', 'MQTT', 'Python', 'C++', 'OPC-UA'],
  },
  {
    id: 'ai-pipelines',
    title: 'AI Pipelines',
    icon: 'Brain',
    description: 'End-to-end ML model development, data pipelines, and AI workflow automation for intelligent business solutions.',
    features: [
      'Custom ML model training & deployment',
      'Data pipeline architecture',
      'Natural language processing solutions',
      'Computer vision applications',
      'AI workflow automation with n8n & LangChain',
    ],
    tech: ['Python', 'TensorFlow', 'PyTorch', 'OpenAI', 'LangChain', 'n8n'],
  },
  {
    id: 'pcb-designing',
    title: 'PCB Designing',
    icon: 'CircuitBoard',
    description: 'Professional PCB design services from schematic capture to manufacturing-ready outputs and prototyping.',
    features: [
      'Schematic design & capture',
      'Multi-layer PCB layout (2-8 layers)',
      'DFM analysis & optimization',
      'Prototype coordination & testing',
      'Component sourcing & BOM management',
    ],
    tech: ['KiCAD', 'Altium Designer', 'Eagle', 'LTSpice', 'JLCPCB'],
  },
  {
    id: 'app-development',
    title: 'App Development',
    icon: 'Smartphone',
    description: 'Cross-platform mobile applications for iOS and Android built with a single codebase for faster delivery.',
    features: [
      'Cross-platform iOS & Android apps',
      'Native performance with shared codebase',
      'Push notifications & real-time features',
      'App Store & Play Store deployment',
      'Backend API integration & offline support',
    ],
    tech: ['React Native', 'Flutter', 'Firebase', 'REST APIs', 'SQLite', 'Redux'],
  },
  {
    id: 'rd-consultancy',
    title: 'R&D Consultancy',
    icon: 'Lightbulb',
    description: 'Technical consulting for new product development, feasibility studies, and innovation strategy.',
    features: [
      'Technical feasibility studies',
      'Product architecture design',
      'Technology stack evaluation',
      'Proof of concept development',
      'Innovation roadmap planning',
    ],
    tech: ['Custom Stack', 'Agile', 'Scrum', 'Documentation', 'Prototyping'],
  },
]

export const SERVICE_TYPE_LABELS = {
  'web-development': 'Website Development',
  'machine-integration': 'Machine Integration & Automation',
  'ai-pipelines': 'AI Pipelines',
  'pcb-designing': 'PCB Designing',
  'app-development': 'App Development',
  'rd-consultancy': 'R&D Consultancy',
  'general': 'General Enquiry',
}
